### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by lamart1** [Pedrojok01/Import-CryptoData-into-GoogleSheet#3]
Hi. Thank you very much, this helped me a lot. I wanted to send you some coins but your donation page is not working. Please share some ETH or BTC address.

**Comment by Pedrojok01** [comment]
You're very welcome @lamart1. I always forget to update the link, seems like the plugin I was using isn't working anymore. 
BTC (taproot): `bc1pvc6r0y86lw4tfyrwjwhnpcckt8dyyyp4xv433mvrz6p4cewxk4lq0du6t9`
But if you can leave some stars here and there on the repo you like, I'd would grateful already :)
